package com.example.Quoter;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.example.Quoter.domain.Message;
import com.example.Quoter.repos.MessageRepo;

@Controller
public class GreetingController {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private MessageRepo messageRepo;
    
    @GetMapping("/greeting")
    public String greeting(
            @RequestParam(name="name", required=false, defaultValue="World")
            String name, Map<String, Object> model) {
        model.put("name", name);
        return "greeting";
    } 
    
    @GetMapping
    public String main(Map<String, Object> model) {
        Iterable<Message> messages = messageRepo.findAll();
        model.put("messages", messages);
        
        return "main";
    }
}
