package com.example.Quoter.controller;

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import com.example.Quoter.domain.Quote;
import com.example.Quoter.domain.User;
import com.example.Quoter.repos.QuoteRepo;

@Controller
public class MainController {
    @Autowired // This means to get the bean called quoteRepo
               // Which is auto-generated by Spring, we will use it to handle the data
    private QuoteRepo quoteRepo;
    
    @Value("${upload.path}")
    private String uploadPath;
    
    @GetMapping("/")
    public String greeting(Map<String, Object> model) {
        return "greeting";
    }
    
    @GetMapping("/main")
    public String main(@RequestParam(required=false, defaultValue="") String filter, Map<String, Object> model) {
        Iterable<Quote> quotes;
        
        if (filter != null && !filter.isEmpty())
            // get the quotes that have the particular tag.
            quotes = this.quoteRepo.findByTag(filter);
        else
            quotes = this.quoteRepo.findAll();
        
        model.put("quotes", quotes);
        model.put("filter", filter);
        
        return "main";
    }
    
    @PostMapping("/main")
    // the form will be sent to the same page where it was sent from.
    public String add(
            @AuthenticationPrincipal User user,
            @RequestParam String text,
            @RequestParam MultipartFile file,
            @RequestParam String tag, Map<String, Object> model
    ) throws IOException {
        // save the quote to the repository(database).
        Quote quote = new Quote(text, tag, user);
        
        if (file != null && !file.isEmpty()) {
            // create the directory if it doesn't exist.
            File uploadDir = new File(this.uploadPath);
            
            if (!uploadDir.exists())
                uploadDir.mkdirs();
            
            // create a new unique filename to avoid collisions.
            String uuidFilename = UUID.randomUUID().toString();
            String resultFilename = uuidFilename + "." + file.getOriginalFilename();
            
            // upload the file to the directory we pointed.
            file.transferTo(new File(this.uploadPath + resultFilename));
            
            // save the name of the file to a certain quote in the database.
            quote.setFilename(resultFilename);
        }
        
        this.quoteRepo.save(quote);
        
        return "redirect:/main";
    }
}
