package com.example.Quoter.controller;

import com.example.Quoter.domain.Quote;
import com.example.Quoter.domain.User;
import com.example.Quoter.repos.QuoteRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import java.io.IOException;
import java.util.Map;

@Controller
public class MainController {
    @Autowired // This means to get the bean called quoteRepo
               // Which is auto-generated by Spring, we will use it to handle the data
    private QuoteRepo quoteRepo;

    @Value("${upload.path}")
    private String uploadPath;
    
    @GetMapping("/")
    public String greeting(Map<String, Object> model) {
        return "greeting";
    }
    
    @GetMapping("/main")
    public String main(
            @RequestParam(required=false, defaultValue="") String filter,
            Map<String, Object> model,
            @PageableDefault(sort = { "id" }, direction = Sort.Direction.DESC) Pageable pageable
    ) {
        Page<Quote> page;

        if (filter != null && !filter.isEmpty()) {
            // get the quotes that have the particular tag.
            page = this.quoteRepo.findByTag(filter, pageable);
        }
        else {
            page = this.quoteRepo.findAll(pageable);
        }

        model.put("page", page);
        model.put("url", "/main");
        model.put("pagerSequence", ControllerUtils.getPagerSequence(page));
        model.put("filter", filter);

        return "main";
    }
    
    @PostMapping("/main")
    // the form will be sent to the same page where it was sent from.
    public String add(
            @AuthenticationPrincipal User user,
            @Valid Quote quote,
            BindingResult bindingResult,
            @RequestParam("file") MultipartFile file,
            Model model
    ) throws IOException {
        quote.setAuthor(user);

        if (bindingResult.hasErrors()) {
            Map <String, String> errorsMap = ControllerUtils.getErrors(bindingResult);
            model.mergeAttributes(errorsMap);
            model.addAttribute("quote", quote);
        } else {
            ControllerUtils.saveFile(file, uploadPath, quote);

            this.quoteRepo.save(quote);
            // remove the quote from the model. Or else, when successful adding a quote, the user will see
            // the open form with the fields filled with the text that the user just added.
            model.addAttribute("quote", null);
        }
        
        Iterable<Quote> quotes = this.quoteRepo.findAll();

        model.addAttribute("quotes", quotes);
        
        return "main";
    }

}
